### PR TITLE
Respect attributes in multipage output

### PR DESCRIPTION
**Pull request by ob**
Pass the document attributes to the multipage generator.
Also generate better filenames for the chunks.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Can you resubmit this PR to https://github.com/owenh000/asciidoctor-multipage?

**Comment by mojavelinux** [comment]
@owenh000 Is this PR of interest to asciidoctor-multipage?

**Comment by owenh000** [comment]
I think the asciidoctor-multipage extension already includes the equivalent of these changes. However, @ob, please do resubmit this to <https://github.com/owenh000/asciidoctor-multipage> it is needed there.

**Comment by mojavelinux** [comment]
:+1:

**Pull request closed without merging**
