### PR TITLE
Create index-markup-inline-macro.rb

### PR DESCRIPTION
**Pull request by andrewcarver**
This is the registration-file for a new extension that supports doing all DocBook's indexing-markup in AsciiDoctor. (
[indexmarkup-inline-macro.zip](https://github.com/asciidoctor/asciidoctor-extensions-lab/files/1911707/indexmarkup-inline-macro.zip)
I've attached a zip-file containing the sample.adoc and the extension.rb, also the registration-file.)

### CODE REVIEW

**Comment by andrewcarver** [comment]
The sample.adoc gives an explanation (hoped not to be overlong) of the extension's functionality.

**Comment by mojavelinux** [comment]
Could you add all the files from the zip to the PR?

**Comment by andrewcarver** [comment]
I'm sorry, I guess I don't know how to do that? Lemme poke around and try to figure it out... unless you can just tell me which button to click when :D

**Comment by andrewcarver** [comment]
BTW, I did try, before uploading the zip, to upload just the separate files. Wouldn't accept the file-types...

**Comment by andrewcarver** [comment]
I guess I've got to go back to my branch and add them there. Sorry, it's been too long between Git adventures...

**Comment by andrewcarver** [comment]
Well, dang it, I managed to add the whole folder--but not in the "lib" folder!! Now I can't undo it-- this is Git, right?!? So, does that mean I need to start a new PR??

**Comment by andrewcarver** [comment]
I'll try that--new PR here we come.

**Comment by andrewcarver** [comment]
Wow.... got the folder in the right place that time, but somehow the registration file ended up NOT in the lib folder... I'm gonna give this one more shot, going with a new PR again!

**Comment by mojavelinux** [comment]
It's actually fine to keep appending the same branch / PR. We can always go back and clean it up later before merging. A PR is like a sandbox...so you can't really mess it up ;)

**Comment by mojavelinux** [comment]
Looks like you got it!

**Comment by mojavelinux** [comment]
Oh, yeah, it's not in the lib folder. Just use `git mv` to move the files. (It's like regular mv except git tracks it).

**Comment by andrewcarver** [comment]
Let's leave this and jump on train #88 ;)

**Comment by andrewcarver** [comment]
Appreciate your patience, Dan!

**Comment by andrewcarver** [comment]
On this original PR's branch (patch-1), I did just now get the extension's folder moved into the lib folder, where it was supposed to be. (I'm not much of a Gitter on the command line, but it occurred to me this was easy-peasy on GitHub Desktop too ;)
So now there are two PRs for this extension (#87 and #88) that have the files and folders in the right place.. If you don't care which one we use, I'll just pick one and close it. Sorry for the tempest in a teapot.

**Comment by andrewcarver** [comment]
Credit where due: The inspiration for this extension was (not surprisingly) solely from [http://discuss.asciidoctor.org/Specialized-Indexes-in-Asciidoc-to-Docbook-backend-td3203.html](url)

**Pull request closed without merging**
