### PR TITLE
Adds twemoji integration

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by Mogztter** [comment]
@mojavelinux Could you please review this PR ?

**Comment by mojavelinux** [comment]
Yep! I sent a code review pull request. See commit message for details. Looking good!

**Comment by mojavelinux** [comment]
One additional thing I'd like to see is shorthand for writing emoji. This would be very similar to the [mentions inline macro](https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/mentions-inline-macro.rb). We can do this in a separate pull request if you want. I just wanted to mention it.

GitHub-flavored markdown and other systems use the syntax of surrounding colons (e.g., `:heart:`). However, that's obviously going to conflict with document-level attribute entries. We could either use surrounding pipes (e.g., `|heart|`) or make the trailing colon optional like a Ruby symbol (e.g., `:heart`).

**Comment by Mogztter** [comment]
I think `:heart` is better because it's closer to other well-known syntax. Plus when I want to add an emoji I usually start typing `:` then the name of the emoji but I never type the trailing colon so `:heart` feels natural.

> Yep! I sent a code review pull request. See commit message for details. Looking good!

Thanks!

> We can do this in a separate pull request if you want. I just wanted to mention it.

Yes I think it's better, I also want to Javascriptify this extension to make it available in the Chrome extension.

**Comment by mojavelinux** [comment]
:+1:

I share that instinct / habit. Let's move forward with the leading colon
idea.

**Comment by mojavelinux** [comment]
Nice work!

I think we're good to go. We'll address any enhancements or improvements (including the shorthand syntax) in follow-up pull requests.

**Pull request merged**
