### PR TITLE
Improve MultipageHtml5Converter extension

### PR DESCRIPTION
**Pull request by owenh000**
Add many features to the MultipageHtml5Converter extension, including
cross-reference support, configurable variable chunking depth, dynamic
Table Of Contents, and page navigation links.

See also <https://github.com/asciidoctor/asciidoctor/issues/626>.

### CODE REVIEW

**Comment by thoni56** [comment]
Would really like to see this merged!

**Comment by minad** [comment]
@owenh000 I am getting warnings "instance variable @number not initialized" on line 117 of the multipage plugin

**Comment by owenh000** [comment]
@minad, I think you are attempting to use the extension with Asciidoctor 1.5.8. Please see the [Notes and limitations](https://github.com/owenh000/asciidoctor-extensions-lab/blob/improve-multipagehtml5/lib/multipage-html5-converter.rb#L26) section in the extension header. The extension needs to be updated to work with Asciidoctor 1.5.8.

**Comment by minad** [comment]
@owenh000 I see, I am using 1.5.8

**Comment by rv0** [comment]
Anyone tried to update it?

**Comment by owenh000** [comment]
I moved the extension into a separate [repository](https://github.com/owenh000/asciidoctor-multipage). Contributions are welcome there. Closing this merge request.

**Pull request closed without merging**
